### ISSUE TITLE
Q2: Request to add tracking to a new jobs page within WordPress

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#15]
Add promo view and promo click to digital directorate jobs page. 
The following GTM object will need to server side and only be fired on a particular page (URL/WordPress page id to be provided) and push the following to the dataLayer.

## FE Dev task
- [ ] Push to the DataLayer when the page loads
```
"ecommerce": {
"promoView": {
      "promotions": [{
        "id": "ddj",
        "name": "Digital directorate jobs",
        "creative": "Landing page",
        "position": "Whole page"
      }]
    }
}
```

- [ ] Push to the Datalayer when someone clicks on the link to the civil service jobs website.

```
 "event": "promotionClick",
  "ecommerce": {
    "promoClick": {
      "promotions": [{
        "id": "ddj",
        "name": "Digital directorate jobs",
        "creative": "Landing page",
        "position": "Where ever the to the link to civil service jobs is" //Please change to the position of the link
      }]
    }
  }
```

**Comment by piriyapordes** [comment]
contradicts privacy policy?

**Comment by hoake** [comment]
Never heard anything back from HR so closed and archived this issue
