### ISSUE TITLE
Ecommerce bug for receipt page

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#99]
## Script development for
- [x] Discovery

#### Ecommerce tracking
- [x] Remove **action: "purchase"** from the Checkout and Purchase actionFields
- [ ]  **event: "checkoutOption"** is appearing everywhere in the ecommerce script
- [x] Reinstate receipt page - purchase fields that seem to have disappeared.
```
"ecommerce": {
    "checkout": {
      "actionField": {
           action: "purchase" // This needs removing
           "step": 1
      },
```
#### For Purchase actionFields only (/receipt page)
```
"ecommerce": {
    "purchase": {
      "actionField": {
          "affiliation": Discovery store
          "tax ": 0
          "shipping": 0
          "revenue": 26, //use meta tag <meta name="WT.tx_total" content="&#163;3.50"> to get the revenue value
          "step": 4
      },
```

## Acceptance/test criteria
In dataLayer for checkout process
Steps 1 to 3:
ecommerce:
**checkout:**
actionField:
step: "**1**" (or 2 or 3)

products: Array(1)
brand: "The National Archives"
category: "Digital item"
id: "PROB 11/275/301"
name: "PROB 11"
price: "3.50"
quantity: 1

On receipt page:
ecommerce:
**purchase:**
actionField:
affiliation: Discovery store
tax : 0
shipping: 0
revenue: 26, //use meta tag <meta name="WT.tx_total" content="&#163;3.50"> to get the revenue value
step: "**4**" 

products: Array(1)
brand: "The National Archives"
category: "Digital item"
id: "PROB 11/275/301"
name: "PROB 11"
price: "3.50"
quantity: 1

**Comment by hoake** [comment]
Currently there are 2 versions of test discovery, one for the cloud and one on-prem. Test on cloud is working but not on-prem. The scripts are running as expected but need to check the on-prem environment before release as live is taken from here.

**Comment by AshTNA** [comment]
@hoake I think we may need to speak to Andrew C about deploying this - I believe the fixed code was already merged into master on Discovery, but I think master on Discovery is currently incompatible with our old servers as everything has been changed to work with the cloud. (This may be a false assumption though.)  May be useful to ask Andy how he managed to get Rebel Christmas up in the Mega Menu for Discovery, as I think he may of had to ask Andrew to do it manually.

If this is a priority fix we may need one of the Discovery developers to implement the new script for us if we want it LIVE before the cloud release.
